# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestScript1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_script1(self):
    self.driver.get("https://www.avito.ru/women-home/")
    self.driver.set_window_size(1294, 1440)
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_overlay_1qhv1_6")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_input_85sal_19").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_input_85sal_19").send_keys("кроссовки")
    self.driver.find_element(By.CSS_SELECTOR, ".x-button_primaryPremium").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_girls_1a2f8_51 > .\\_image_1a2f8_16")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#RTLAEU382601 .\\_area_552z7_8").click()
  
