# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestScript4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_script4(self):
    self.driver.get("https://www.avito.ru/women-home/")
    self.driver.set_window_size(1294, 1440)
    self.driver.find_element(By.CSS_SELECTOR, ".\\_input_85sal_19").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_input_85sal_19").send_keys("кроссовки")
    self.driver.find_element(By.CSS_SELECTOR, ".icon__search-white").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#RTLAEU382601 .\\_area_552z7_8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#RTLAEU382601 .\\_area_552z7_8").click()
    self.driver.find_element(By.CSS_SELECTOR, ".x-button_primaryPremium > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_colspan_14ypi_152:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".x-button_primaryPremium > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_aside_1oekg_45").click()
  
