# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestScript5():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_script5(self):
    self.driver.get("https://www.avito.ru/women-home/")
    self.driver.set_window_size(1294, 1440)
    self.driver.find_element(By.CSS_SELECTOR, ".\\_input_85sal_19").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_input_85sal_19").send_keys("dfgdsfyery")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_input_85sal_19").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".\\_title_tt0cu_24").click()
    element = self.driver.find_element(By.LINK_TEXT, "Аксессуары")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_input_85sal_19").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_root_qai5c_2:nth-child(2) .\\_overlay_1qhv1_6")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "#RTLAEU382601 .\\_area_552z7_8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#RTLAEU382601 .\\_area_552z7_8").click()
  
